version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chess_lessons
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/chess_lessons
      - SECRET_KEY=your-super-secret-key-change-in-production
      - DO_SPACES_KEY=your-do-spaces-key
      - DO_SPACES_SECRET=your-do-spaces-secret
      - DO_SPACES_ENDPOINT=https://fra1.digitaloceanspaces.com
      - DO_SPACES_BUCKET=chess-lessons-videos
      - KASPI_PAY_API_KEY=your-kaspi-api-key
      - KASPI_PAY_MERCHANT_ID=your-merchant-id
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
