"""rm created at

Revision ID: 1c792abff75a
Revises: 9ceb72bed778
Create Date: 2025-07-20 22:37:10.996485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c792abff75a'
down_revision: Union[str, Sequence[str], None] = '9ceb72bed778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_types', 'created_at')
    op.drop_column('attribute_values', 'created_at')
    op.alter_column('videos', 'access_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'access_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('attribute_values', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('attribute_types', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
