"""replace chess_level str with foreign key

Revision ID: e73890c6c1b4
Revises: 1c792abff75a
Create Date: 2025-07-27 22:29:26.973029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73890c6c1b4'
down_revision: Union[str, Sequence[str], None] = '1c792abff75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chess_level_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'attribute_values', ['chess_level_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'chess_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chess_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'chess_level_id')
    # ### end Alembic commands ###
